# Trivy Secret Scanning Configuration
# Documentation: https://aquasecurity.github.io/trivy/latest/docs/scanner/secret/

# Enable secret scanning
secret:
  enabled: true

  # Secret detection rules
  rules:
    # AWS credentials
    - id: aws-access-key-id
      category: AWS
      title: AWS Access Key ID
      severity: HIGH
      regex: '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'

    - id: aws-secret-access-key
      category: AWS
      title: AWS Secret Access Key
      severity: CRITICAL
      regex: 'aws(.{0,20})?[''"][0-9a-zA-Z\/+]{40}[''"]'

    # Google Cloud
    - id: gcp-api-key
      category: GCP
      title: Google Cloud API Key
      severity: HIGH
      regex: 'AIza[0-9A-Za-z\-_]{35}'

    - id: gcp-service-account
      category: GCP
      title: Google Cloud Service Account
      severity: CRITICAL
      regex: '"type"\s*:\s*"service_account"'

    # GitHub
    - id: github-token
      category: GitHub
      title: GitHub Token
      severity: HIGH
      regex: 'gh[pousr]_[A-Za-z0-9_]{36,}'

    - id: github-app-token
      category: GitHub
      title: GitHub App Token
      severity: HIGH
      regex: '(ghu|ghs|ghr)_[A-Za-z0-9_]{36,}'

    # Private Keys
    - id: private-key
      category: AsymmetricPrivateKey
      title: Private Key
      severity: CRITICAL
      regex: '-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'

    # Generic secrets
    - id: generic-api-key
      category: Generic
      title: Generic API Key
      severity: MEDIUM
      regex: '(?i)(api[_-]?key|apikey|api[_-]?token)\s*[=:]\s*[''"]?[a-zA-Z0-9\-_]{20,}[''"]?'

  # Exclude patterns
  exclude:
    paths:
      - '**/*.example'
      - '**/*.sample'
      - '**/*.template'
      - '**/test/**'
      - '**/tests/**'
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/docs/**'
      - '**/examples/**'
      - '**/.env.example'
      - '**/node_modules/**'

    # Patterns to exclude from secret detection
    allow-rules:
      - id: test-key
        regex: 'test[_-]?(key|token|secret|password)'
      - id: example-key
        regex: 'example[_-]?(key|token|secret|password)'
      - id: dummy-key
        regex: 'dummy[_-]?(key|token|secret|password)'
      - id: placeholder
        regex: 'your[_-]?(key|token|secret|password|value)'
